declare namespace componyx 
{
    namespace UI
    {
        interface PieChart extends Omit<componyx.UI.base.methods, 'render' | 'destroy' | 'cloneProperties' | 'postRender'> { }
        /**
         * <p>PieChart class.</p>
         * @param id - <p>The id of the component.</p>
         * @param properties - <p>The properties used to initialize the component or the container element.</p>
         */
        class PieChart extends componyx.UI.base.WebComponent
        {
            constructor(id?: string, properties?: any | HTMLElement);
            /**
             * <p>Internal CSS class name constants. You can override any of these classes on the Component
             * instance by defining a property named <code>cssClass&lt;Key&gt;</code> where &lt;Key&gt; is the
             * PascalCase key from this object. Be cautious: overriding these classes without including the
             * default names may break styling and functionality.</p>
             */
            readonly classOption: {
                readonly CHART: string;
                readonly HALF: string;
                readonly DONUT: string;
                readonly LEGEND: string;
                readonly LEGEND_ITEM: string;
                readonly LEGEND_ITEM_COLOR: string;
                readonly LEGEND_ITEM_LABEL: string;
                readonly SEGMENT_LABEL: string;
                readonly SEGMENT_OVERLAY: string;
                readonly SEGMENT_HOVER: string;
            };
            /**
             * <p>PieChart events</p>
             */
            events: componyx.UI.PieChart.PieChartEvents;
            /**
             * <p>Renders the component.</p>
             */
            render(): void;
            /**
             * <p>Destroys the component.</p>
             * @param keepEvents - <p>A value indicating if component events should be kept.</p>
             * @param [removeElement = true] - <p>A value indicating if the corresponding HTML Element should be removed.</p>
             */
            destroy(keepEvents: boolean, removeElement?: boolean): void;
            /**
             * <p>Gets the css class if it exists and otherwise the default css class.</p>
             * @param cssClassValue - <p>The class option key to look up.</p>
             * @returns <p>The css class.</p>
             */
            getCssClass(cssClassValue: string): string;
            /**
             * <p>Gets or sets the shape of the pie chart (PIE or DONUT).</p>
            */
            shape: componyx.UI.PieChart.ShapeOption;
            /**
             * <p>Gets or sets where the segment labels are displayed (NONE, INNER, or OUTER).</p>
            */
            segmentLabelDisplay: componyx.UI.PieChart.SegmentLabelDisplayOption;
            /**
             * <p>Gets or sets the content of the segment labels (VALUE, LABEL, LABEL_VALUE).</p>
            */
            segmentLabelContent: componyx.UI.PieChart.SegmentLabelContentOption;
            /**
             * <p>Gets or sets a value indicating whether the chart spans half a circle.</p>
            */
            isHalf: boolean;
            /**
             * <p>Gets or sets a value indicating whether the legend is displayed.</p>
            */
            showLegend: boolean;
            /**
             * <p>Gets or sets a value indicating whether segment values are shown in the legend labels.</p>
            */
            showValuesInLegend: boolean;
            /**
             * <p>Gets or sets the start angle in degrees (0 = top, clockwise). Only applies to the full (non-half) variant.</p>
            */
            startAngle: number;
            /**
             * <p>Gets or sets the inner hole size for the donut variant as a ratio (0-1, where 0.6 = 60% hole).</p>
            */
            donutInnerRatio: number;
            /**
             * <p>Gets or sets the base color used for segments without a specified color. The colors of such segments are generated by shifting the hue of the base color.</p>
            */
            baseColor: string;
            /**
             * <p>Gets or sets the segment label positioning offset. For OUTER labels: distance in pixels from chart edge (default: 20). For INNER labels: position ratio from 0 (inner edge) to 1 (outer edge) (default: 0.5).</p>
            */
            segmentLabelOffset: number | null;
            /**
             * <p>Gets or sets the list of segments.</p>
            */
            segments: componyx.UI.PieChart.Segment[];
            /**
             * <p>Gets or sets the id of the component from which the settings are cloned for the tooltip manager used by the PieChart component.</p>
            */
            tooltipManagerId: string;
        }
        namespace PieChart
        {
            /**
             * @property onSegmentEnter - <p>Fires when the pointer enters a segment.</p>
             * @property onSegmentLeave - <p>Fires when the pointer leaves a segment.</p>
             * @property onSegmentClick - <p>Fires when a segment is clicked.</p>
             * @property onRenderSegmentLabel - <p>Fires when a segment label is rendered.</p>
             * @property onRenderLegendLabel - <p>Fires when a legend label is rendered.</p>
             */
            class PieChartEvents extends componyx.UI.base.Events<componyx.UI.PieChart>
            {
                constructor();
                /**
                 * <p>Fires when the pointer enters a segment.</p>
                */
                onSegmentEnter: componyx.UI.base.Event<componyx.UI.PieChart, componyx.UI.PieChart.PieChartEventArgs>;
                /**
                 * <p>Fires when the pointer leaves a segment.</p>
                */
                onSegmentLeave: componyx.UI.base.Event<componyx.UI.PieChart, componyx.UI.PieChart.PieChartEventArgs>;
                /**
                 * <p>Fires when a segment is clicked.</p>
                */
                onSegmentClick: componyx.UI.base.Event<componyx.UI.PieChart, componyx.UI.PieChart.PieChartEventArgs>;
                /**
                 * <p>Fires when a segment label is rendered.</p>
                */
                onRenderSegmentLabel: componyx.UI.base.Event<componyx.UI.PieChart, componyx.UI.PieChart.PieChartLabelRenderEventArgs>;
                /**
                 * <p>Fires when a legend label is rendered.</p>
                */
                onRenderLegendLabel: componyx.UI.base.Event<componyx.UI.PieChart, componyx.UI.PieChart.PieChartLabelRenderEventArgs>;
            }
            /**
             * <p>PieChart segment event arguments.</p>
             */
            type PieChartEventArgs = {
                /** <p>The data segment.</p> */
                segment: componyx.UI.PieChart.Segment;
                /** <p>The original event object.</p> */
                event: Event;
            };
            /**
             * <p>PieChart label render event arguments.</p>
             */
            type PieChartLabelRenderEventArgs = {
                /** <p>The data segment.</p> */
                segment: componyx.UI.PieChart.Segment;
                /** <p>The label DOM element (segment label or legend label) that can be customized.</p> */
                element: HTMLElement;
            };
            /**
             * <p>Represents a chart segment.</p>
             * @param [properties] - <p>The properties used to initialize the object.</p>
             */
            class Segment
            {
                constructor(properties?: {
                    id?: string;
                    label?: string;
                    tooltip?: string;
                    color?: string;
                    value?: number;
                    valueSuffix?: string;
                    endColor?: string;
                });
                /**
                 * <p>Gets or sets the id of the segment.</p>
                */
                id: string;
                /**
                 * <p>Gets or sets the label of the segment</p>
                */
                label: string;
                /**
                 * <p>Gets or sets the tooltip of the segment</p>
                */
                tooltip: string;
                /**
                 * <p>Gets or sets the CSS color value of the segment.</p>
                */
                color: string;
                /**
                 * <p>Gets or sets the value of the segment.</p>
                */
                value: number;
                /**
                 * <p>Gets or sets the value suffix (e.g. %) of the segment.</p>
                */
                valueSuffix: string;
                /**
                 * <p>Gets or sets the optional CSS end color value of the segment.</p>
                */
                endColor: string | null;
            }
            /**
             * <p>ShapeOption</p>
             */
            enum ShapeOption
            {
                PIE = "pie",
                DONUT = "donut"
            }
            /**
             * <p>SegmentLabelDisplayOption</p>
             */
            enum SegmentLabelDisplayOption
            {
                NONE = "none",
                INNER = "inner",
                OUTER = "outer"
            }
            /**
             * <p>SegmentLabelContentOption</p>
             */
            enum SegmentLabelContentOption
            {
                VALUE = "value",
                LABEL = "label",
                LABEL_VALUE = "label_value"
            }
        }
    }
}